-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 10, 2025 at 06:11 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `travelbus`
--

-- --------------------------------------------------------

--
-- Table structure for table `buses`
--

CREATE TABLE `buses` (
  `id` int(11) NOT NULL,
  `bus_name` varchar(100) NOT NULL,
  `bus_type` varchar(50) DEFAULT NULL,
  `departure` varchar(255) NOT NULL,
  `destination` varchar(255) NOT NULL,
  `departure_time` varchar(20) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `rewards` varchar(50) DEFAULT NULL,
  `facility_images` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`facility_images`)),
  `logo_url` varchar(255) DEFAULT NULL,
  `booking_url` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `buses`
--

INSERT INTO `buses` (`id`, `bus_name`, `bus_type`, `departure`, `destination`, `departure_time`, `date`, `price`, `rewards`, `facility_images`, `logo_url`, `booking_url`, `created_at`, `updated_at`) VALUES
(5, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '1:45 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(6, 'Daewoo Express', 'Gold Class', 'Lahore Thokar', 'Multan', '1:45 PM', '2025-04-09', 2580.00, '258', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(7, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '2:15 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(8, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '2:15 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(9, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '2:30 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(10, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '2:45 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(11, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '2:45 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(12, 'Daewoo Express', 'Super Luxury', 'Lahore Thokar - VIA G.T ROAD', 'Multan', '3:00 PM', '2025-04-09', 1650.00, '165', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(13, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '3:15 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(14, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '3:15 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(15, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '3:45 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(16, 'Daewoo Express', 'Gold Class', 'Lahore Kalma Chowk', 'Multan', '4:15 PM', '2025-04-09', 2770.00, '277', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(17, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '4:30 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(18, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '4:30 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(19, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '4:45 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(20, 'Daewoo Express', 'Gold Class', 'Lahore Thokar', 'Multan', '4:45 PM', '2025-04-09', 2580.00, '258', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(21, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '5:00 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(22, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '5:15 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(23, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '5:15 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(24, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '5:45 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(25, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '5:45 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(26, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '6:15 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(27, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '6:15 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(28, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '6:45 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(29, 'Daewoo Express', 'Gold Class', 'Lahore Kalma Chowk', 'Multan', '7:15 PM', '2025-04-09', 2770.00, '277', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(30, 'Daewoo Express', 'Gold Class', 'Lahore Thokar', 'Multan', '7:45 PM', '2025-04-09', 2580.00, '258', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(31, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '8:15 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(32, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '8:45 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(33, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '9:15 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(34, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '9:45 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(35, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '10:00 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(36, 'Daewoo Express', 'Gold Class', 'Lahore Kalma Chowk', 'Multan', '10:15 PM', '2025-04-09', 2770.00, '277', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(37, 'Daewoo Express', 'Gold Class', 'Lahore Thokar', 'Multan', '10:45 PM', '2025-04-09', 2580.00, '258', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(38, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '11:00 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(39, 'Daewoo Express', 'Luxury', 'Lahore Kalma Chowk', 'Multan', '11:15 PM', '2025-04-09', 2240.00, '224', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(40, 'Daewoo Express', 'Gold Class', 'Lahore Thokar', 'Multan', '11:30 PM', '2025-04-09', 2580.00, '258', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(41, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Multan', '11:45 PM', '2025-04-09', 2040.00, '204', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:39:01', '2025-04-09 07:39:01'),
(42, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Peshawar', '4:30 PM', '2025-04-09', 2800.00, '280', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:42:04', '2025-04-09 07:42:04'),
(43, 'Daewoo Express', 'Luxury', 'Lahore Thokar', 'Peshawar', '4:30 PM', '2025-04-09', 2800.00, '280', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/headphone.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/ac.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-09 07:43:59', '2025-04-09 07:43:59'),
(44, 'Daewoo Express', 'Luxury', 'Multan', 'Dera Ghazi Khan', '1:15 PM', '2025-04-10', 570.00, '57', '[\"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/free_wifi.png?images=true\", \"https://bkme.s3.me-south-1.amazonaws.com/static/assets/img/transport_facility/V5/regular_seat.png?images=true\"]', 'https://bkme.s3.me-south-1.amazonaws.com/static/custom/upload/transport/daewoo-express.jpg', 'https://bookme.pk/bus/search-results', '2025-04-10 03:48:55', '2025-04-10 03:48:55');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `buses`
--
ALTER TABLE `buses`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `buses`
--
ALTER TABLE `buses`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
